spring:
  profiles:
    active: dev
  messages:
    encoding: UTF-8

slack:
  bot-token: ${SLACK_BOT_TOKEN}
  signing-secret: ${SLACK_SIGNING_SECRET}

openai:
  api-key: ${OPENAI_API_KEY}
  url: https://api.openai.com/v1/chat/completions
  model: gpt-4o-mini
