spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_batch_fetch_size: 1000
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    com.jia.study_tracker.slack.SlackEventService: DEBUG

slack:
  verify-signature: false
  enabled: false
