spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/growthtracker
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        default_batch_fetch_size: 1000

  redis:
    host: localhost
    port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    com.jia.study_tracker.slack.SlackEventService: DEBUG

slack:
  verify-signature: false
  enabled: false